### ISSUE TITLE
代码呢？？？

### ISSUE THREAD

**Issue by MasterSumCloud** [Tamicer/FastDownloader#1]
不把代码贴出来 干毛？？

**Comment by Tamicer** [comment]
@MasterSumCloud maven包就是代码 没有混淆

**Comment by tanshion** [comment]
@Tamicer 你好，你提供的compile 'com.tamic.fastdownloader:Android-FastDownloader:1.0.0'  在gradle下载不到包呢

**Comment by Tamicer** [comment]
@MasterSumCloud 请更新
