### ISSUE TITLE
下载之后后 删除功能吗？批量删除？

### ISSUE THREAD

**Issue by Keko2025** [Tamicer/FastDownloader#6]

**Comment by Tamicer** [comment]
能的 ，有个deleteAll（）

**Comment by Keko2025** [comment]
可以对单个item进行删除的方法？

**Comment by Tamicer** [comment]
@18710891669 deleteKey(Sting key)

**Comment by Tamicer** [comment]
@18710891669  RxDownLoadCenter.getInstance(mContext).cancelAllDownloaded();
